CREATE DATABASE IF NOT EXISTS CRUD_DW;
USE CRUD_DW;

CREATE TABLE PROFILE_(
    PROFILE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR (40) UNIQUE,
    USER_NAME VARCHAR (30) UNIQUE,
    PSWD VARCHAR (255),
    TELEPHONE BIGINT,
    NAME_ VARCHAR (30),
    SURNAME VARCHAR (30)
);


CREATE TABLE USER_(
    PROFILE_CODE INT PRIMARY KEY,
    GENDER VARCHAR (10),
    CARD_NO VARCHAR (50),
    FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE ADMIN_(
    PROFILE_CODE INT PRIMARY KEY,
    CURRENT_ACCOUNT VARCHAR (50),
    FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE VIDEOGAME_(
    V_CODE INT PRIMARY KEY AUTO_INCREMENT,
    V_NAME VARCHAR(50) NOT NULL,
    V_RELEASE DATE NOT NULL,
    V_PLATFORM ENUM('PC', 'NINTENDO', 'XBOX', 'PLAYSTATION', 'DEFAULT'),
    V_PEGI ENUM('PEGI3', 'PEGI6', 'PEGI12', 'PEGI16', 'PEGI18', 'DEFAULT')
);


CREATE TABLE LISTED_(
    L_NAME VARCHAR(50),
    PROFILE_CODE INT,
    V_CODE INT,
    PRIMARY KEY (L_NAME, PROFILE_CODE, V_CODE),
    FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (V_CODE) REFERENCES VIDEOGAME_(V_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE REVIEW_(
    PROFILE_CODE INT,
    V_CODE INT,
    R_SCORE INT,
    R_DESCRIPTION VARCHAR(100),
    R_DATE DATE,
    PRIMARY KEY (PROFILE_CODE, V_CODE),
    FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (V_CODE) REFERENCES VIDEOGAME_(V_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);


INSERT INTO PROFILE_ (PROFILE_CODE, EMAIL, USER_NAME, PSWD, TELEPHONE, NAME_, SURNAME) VALUES
    (1, 'juan.perez@email.com', 'juanP', '$2y$10$7OMKfOjQveaUvkRh18Ok8OvWOpSXyAGW0cf/raaZh9Kzk5GucWm6m', 611223344, 'Juan', 'Pérez'),
    (2, 'maria.garcia@email.com', 'mariag', '$2y$10$dVhwoJ9yT8gRbLuBIWiKD.RLiF87h09uDArHwGAlsuH/0CxTBC0da', 622334455, 'María', 'García'),
    (3, 'carlos.lopez@email.com', 'carlosl', '$2y$10$cJRVfsmypj/dUfqSlpX0wuoBULPDkSEOGTXBxt627KWp5TuVL5lPG', 633445566, 'Carlos', 'López'),
    (4, 'ana.martinez@email.com', 'anam', '$2y$10$w04egwZMKEDPgTm8IU4QQeIbfFsdd0dPXBu1HVa81DQgEAcaQgWOm', 644556677, 'Ana', 'Martínez'),
    (5, 'pedro.rodriguez@email.com', 'pedror', '$2y$10$3qVuwp5IecRyRoHP2So0v.WeQMzBLeTs.O6s.NWb/Nqv.KpQrtX8G', 655667788, 'Pedro', 'Rodríguez');


INSERT INTO USER_ (PROFILE_CODE, GENDER, CARD_NO) VALUES
    (1, 'Man', '1234-5678-9012-3456'),
    (2, 'Female', '2345-6789-0123-4567'),
    (3, 'Man', '3456-7890-1234-5678');


INSERT INTO ADMIN_ (PROFILE_CODE, CURRENT_ACCOUNT) VALUES
    (4, 'ES12-3456-7890-1234-5678'),
    (5, 'ES98-7654-3210-9876-5432');

INSERT INTO VIDEOGAME_ (V_NAME, V_RELEASE, V_PLATFORM, V_PEGI) VALUES
    ('COD', '2025-06-06', 'PC', 'PEGI18'),
    ('FIFA', '2025-07-07', 'PLAYSTATION', 'PEGI3');

DELIMITER //
CREATE PROCEDURE RegistrarUsuario( IN p_username VARCHAR(30), IN p_pswd VARCHAR(255))
BEGIN
    DECLARE  nuevo_profile_code INT;

    INSERT INTO PROFILE_ (EMAIL, USER_NAME, PSWD, TELEPHONE, NAME_, SURNAME)
    VALUES (null, p_username, p_pswd, null, null, null);

    SET nuevo_profile_code = LAST_INSERT_ID();

    INSERT INTO USER_ (PROFILE_CODE, GENDER, CARD_NO)
    VALUES (nuevo_profile_code, null, null);

    SELECT * FROM PROFILE_ P, USER_ U WHERE P.PROFILE_CODE = U.PROFILE_CODE AND P.PROFILE_CODE= nuevo_profile_code;
 END //

DELIMITER ;
